### PR TITLE
Use a simple decoded string instead of base64 string ...

### PR DESCRIPTION
**Pull request by NgLam2911**
* That a troll msg by JINODK

### CODE REVIEW

**Comment by JINODK** [comment]
Just a simple copyright notice ¯\_(ツ)_/¯

**Comment by NgLam2911** [comment]
LUL

**Comment by JINODK** [comment]
Just in case some inexperienced child clone my code and calling it their code .______.

**Comment by NgLam2911** [comment]
I think they already know how to decode that string :v

**Comment by JINODK** [comment]
i mean `some inexperienced child`
also it's just a reminder, harmless bloatware at startup :)

**Pull request closed without merging**
